### ISSUE TITLE
(SPIKE_1006) [Spike] Storage de archivos

### ISSUE THREAD

**Issue by antonieto** [antonieto/ibm-dashboard#117]

**Comment by Int-Angel** [comment]
- https://supabase.com/docs/guides/storage
- https://www.filestack.com/docs/api/file/

Extra: 
- https://uppy.io/ <- Es un file uploader open source (no carga el archivo en la nube)

Nota:
Yo creo que hay que utilizar el mas facil de implementar, pero de una manera muy modular para que sea facil de cambiar para IBM a su servidor de archivos propio.
